### ISSUE TITLE
Error: Invalid site key or not loaded in api.js: <key>

### ISSUE THREAD

**Issue by felipecastrosales** [Zujaj/recaptcha_v3_tutorial#2]
How fix it? I'm facing with this error in my app. 

When I clone this, I see the same error. Any expectations or fix suggested?

**Comment by felipecastrosales** [comment]
cc @Zujaj let me see if you know this error and how fix

**Comment by Zujaj** [comment]
@felipecastrosales I apologize for the late response, I have a very busy schedule. My suggestion is that you kindly read the configuration steps mentioned in the README file and replace the placeholder values with your actual ones. I tried to reproduce the error by just cloning the project, installing the pub packages and running it.

![image](https://github.com/Zujaj/recaptcha_v3_tutorial/assets/46039324/ab053177-099f-4448-8037-cd1aef9ecfc9)

Also, I plan to replace this repo with a new one that would demonstrate proper implementation of recaptcha flutter web app with Nodejs backend.
